<form id="redirect_form" action="<?php echo $this->getBaseUrl(); ?>" method="GET">
    <p>"You are transferred to PagaLu's secure payment environment. <input type='submit' value='Click here'> if you are not automatically transferred."
</form>

<script type="text/javascript">

    function getJsonData(url, callback) {
        let request = new XMLHttpRequest;
        let timer = setTimeout(function() {
            getJsonData(url, callback);
        }, 10000);
        request.onreadystatechange = function() {
            if (request.readyState === 4 && request.status === 200) {
                clearTimeout(timer);
                return callback(JSON.parse(request.responseText));
            }
        }
        request.open('GET', url);
        request.send();
    }

    var jsonUrl = "<?php echo $this->getBaseUrl(); ?>/pagalu/payment/view/";
    var myData;
    getJsonData(jsonUrl, function(data) {
        myData = data;
        redirect_url = myData.url;

        // Fallback update user URL
        var form = document.getElementById("redirect_form");
        form.action = redirect_url;

        window.location.replace(redirect_url);
    });

</script>
